server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://host.docker.internal:4003
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-patient
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth
          uri: http://host.docker.internal:4003
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

logging:
  level:
    root: info
management:
  endpoint:
    health:
      show-details: always